add_newline = false

# Main format string
format = "$username@$hostname:$directory$python$direnv$git_branch$git_status$status$jobs$cmd_duration$character"

[username]
format = "[$user]($style)"
style_user = "green"
style_root = "red"
show_always = true

[hostname]
format = "[$hostname]($style)"
style = "cyan"
ssh_only = false

[directory]
format = "[$path]($style)"
style = "141"
truncation_length = 2
truncation_symbol = "…/"
truncate_to_repo = false
home_symbol = "~"

[python]
format = " [${virtualenv}]($style)"
style = "blue"
detect_extensions = []
detect_files = []
detect_folders = []

[direnv]
disabled = false
format = " [direnv]($style)"
style = "yellow"

[status]
disabled = false
format = " [exit:$status]($style)"
style = "red"
map_symbol = true

[git_branch]
format = " [$branch]($style)"
style = "yellow"

[git_status]
disabled = false
format = "[$conflicted$deleted$modified$renamed$staged$untracked$ahead_behind]($style)"
style = "red"
staged = "+"
modified = "!"
deleted = "x"
renamed = "»"
untracked = "?"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = ""

[cmd_duration]
min_time = 50
show_milliseconds = true
format = " [$duration]($style)"
style = "yellow"

[jobs]
symbol = "+"
style = "blue"
number_threshold = 1
format = " [$symbol$number]($style)"

[character]
success_symbol = " [»](bold green)"
error_symbol = " [»](bold red)"
